#!/bin/sh
# git ブランチ作成
if [ $# -eq 0 ]; then
    printf "branch name: "
    read branch_name
else
    branch_name="$1"
fi

if [ -n "$branch_name" ]; then
    git switch -c "$branch_name"
else
    echo "Branch name is required."
    exit 1
fi
