#!/bin/sh
# codex ラッパー
if [ "$1" = "update" ]; then
    npm install -g @openai/codex@latest
else
    codex \
        --dangerously-bypass-approvals-and-sandbox \
        -c model_reasoning_summary_format=experimental \
        --search "$@"
fi
