#!/bin/sh
# tmux: "default" セッションに attach、なければ作成

session_name="default"

if tmux has-session -t "$session_name" 2>/dev/null; then
    tmux attach-session -t "$session_name"
else
    tmux new-session -s "$session_name"
fi
