name: Scripts Test

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test install scripts
        run: make install
      - name: test macos defaults
        run: make macos
      - name: test install applications
        run: make applications
